### ISSUE TITLE
Token für ##admin_email## berücksichtigt nur Einstellungen

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-dca-notification#1]
Wie oben schon geschrieben berücksichtigt das Token ##admin_email## nur den Eintrag in den Einstellungen von Contao. Aber wie überall muss ebenfalls das Feld "E-Mail-Adresse des Webseiten-Administrators" in der Seitenstruktur im Startpunkt der entsprechenden Website beachtet werden.

Also wenn im "Startpunkt der Website" die "E-Mail-Adresse des Webseiten-Administrators" ausgefüllt ist, soll diese genommen werden, wenn das Feld leer ist, dann soll die "E-Mail-Adresse des Systemadministrators" aus den Einstellungen genutzt werden.

**Comment by dmolineus** [comment]
Das geht nicht, da wir uns im Backend-Context befinden. Dort wird immer auf die Systemeinstellung zurückgegriffen. Es spricht nichts dagegen, die E-Mail Adresse händisch zu hinterlegen in der Notification.

**Comment by frontendschlampe** [comment]
öhm ... aber im "normalen" Notification Center ist die Funktionsweise aber genauso?! Wenn in Seitenstruktur was eingetragen, dann das, ansonsten aus den Einstellungen.

**Comment by dmolineus** [comment]
1. Wo werden im "normalen" Notification Center Benachrichtungen aus dem Backend vesandt?
2. Ich nutze wie das Notification Center die Contao-Variable [`TL_ADMIN_EMAIL`](https://github.com/hofff/contao-dca-notification/blob/8a5838bd7738457df37f187de70f830d2d3389b4/src/EventListener/Dca/DataContainerSendingNotificationDcaListener.php#L95). Das Notification Center macht es [genauso](https://github.com/terminal42/contao-notification_center/blob/d20dfdd5ddb409bc8ff606bca62babbeb5076148/library/NotificationCenter/ContaoHelper.php#L104). Wie bei allen seitenbezogenen Einstellungen auch, greift im Backend das Fallback aus der Systemeinstellung.
3. Wie soll denn deiner Meinung nach erkannt werden zu welcher Seite der registrierte Nutzer gehört? Hier werden doch keinerlei Informationen gespeichert?

**Comment by frontendschlampe** [comment]
ahhhhh ... jetzt verstehe ich das Problem! :-D

Alles klar. Wir senden ja aus dem BE. Sorry ... ich stand auf der Leitung. Die "normalen" Notifications greifen ja im FE!
